#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;

use App::PMUtils;
use Perinci::CmdLine::Any;

our %SPEC;
$SPEC{pmman} = {
    v => 1.1,
    summary => 'Show manpage of Perl module',
    description => <<'_',

This function is essentially `man MODNAME`, but offers command-line completion.

_
    args => {
        module => $App::PMUtils::arg_module_single,
    },
    deps => {
        prog => 'man',
    },
};
sub pmman {
    my %args = @_;
    my $mod = $args{module};
    $mod =~ s!/!::!g;
    my @cmd = ("man", $mod);
    exec @cmd;
    # [200]; # unreachable
}

Perinci::CmdLine::Any->new(
    url => '/main/pmman',
    read_config => 0,
    read_env => 0,
)->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

Basic usage:

 % pmman Some::Module


=head1 SEE ALSO

L<pmdoc>, L<pmhtml>

L<lcpan> (C<doc> subcommand)
