#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;

use App::PMUtils;
use Perinci::CmdLine::Any;

our %SPEC;
$SPEC{pmstripper} = {
    v => 1.1,
    summary => 'Strip Perl module source codes using Perl::Stripper',
    args => {
        module => $App::PMUtils::arg_module_multiple,
    },
};
sub pmstripper {
    require Module::Path::More;
    require Perl::Stripper;

    my %args = @_;
    my $mods = $args{module};
    return [400, "Please specify at least one module"] unless @$mods;

    my $stripper = Perl::Stripper->new(
        maintain_linum => $args{stripper_maintain_linum},
        strip_ws       => $args{stripper_ws},
        strip_comment  => $args{stripper_comment},
        strip_pod      => $args{stripper_pod},
        strip_log      => $args{stripper_log},
    );

    my $has_success;
    my $has_error;
    for my $mod (@$mods) {
        $mod =~ s!/!::!g;
        my $path = Module::Path::More::module_path(module=>$mod) or do {
            warn "pmstripper: No such module '$mod'";
            $has_error++;
            next;
        };
        open my $fh, "<", $path or do {
            warn "pmstripper: Can't open '$path': $!\n";
            $has_error++;
            next;
        };
        local $/;
        print $stripper->strip(~~<$fh>);
        close $fh;
        $has_success++;
    }

    if ($has_error) {
        if ($has_success) {
            return [207, "Some modules failed"];
        } else {
            return [500, "All modules failed"];
        }
    } else {
        return [200, "All modules OK"];
    }
}

require PERLANCAR::AppUtil::PerlStripper; PERLANCAR::AppUtil::PerlStripper::_add_stripper_args_to_meta($SPEC{pmstripper});
# since we always strip, we don't need these
for ($SPEC{pmstripper}) {
    delete $_->{args}{stripper};
    delete $_->{args_rels};
}

Perinci::CmdLine::Any->new(
    url => '/main/pmstripper',
    read_config => 0,
    read_env => 0,
)->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

Basic usage:

 % pmstripper Some::Module Another::Module
