#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;
#use Log::Any::IfLOG '$log';

use App::PMUtils;
use Perinci::CmdLine::Any;

Perinci::CmdLine::Any->new(
    url => '/App/PMUtils/rel2mod',
    read_config => 0,
    read_env => 0,
)->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

From command-line arguments:

 % rel2mod Foo-Bar-1.23.tar.gz Baz-v0.01.tar.gz
 Foo::Bar
 Baz

From STDIN:

 % echo -e "Foo-Bar-1.23.tar.gz\nBaz-v0.01.tar.gz" | rel2mod
 Foo::Bar
 Baz


=head1 SEE ALSO
